"""Render findings into a suggest-only Ansible playbook.

prescryb never applies playbooks itself - this module only ever produces text
for a human to review with `ansible-playbook --check` / diff before running.
CVE findings become concrete package-upgrade tasks; config findings that map
to an existing konstruktoid.hardening role are referenced as a role rather
than reimplemented, since that collection is the authoritative source for
those controls.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING

import yaml

if TYPE_CHECKING:
    from prescryb.models import CVEMatch, Finding, SystemInfo

_PKG_MODULE = {
    "debian": "ansible.builtin.apt",
    "redhat": "ansible.builtin.dnf",
    "suse": "community.general.zypper",
    "arch": "community.general.pacman",
    "alpine": "community.general.apk",
}


def _pkg_task_args(os_family: str, package: str, fixed_version: str | None) -> dict:
    if os_family == "debian":
        name = f"{package}={fixed_version}" if fixed_version else package
        return {
            "name": name,
            "state": "present" if fixed_version else "latest",
            "update_cache": True,
        }
    if os_family == "redhat":
        name = f"{package}-{fixed_version}" if fixed_version else package
        return {"name": name, "state": "present" if fixed_version else "latest"}
    if os_family == "suse":
        name = f"{package}={fixed_version}" if fixed_version else package
        return {"name": name, "state": "present" if fixed_version else "latest"}
    if os_family == "alpine":
        name = f"{package}={fixed_version}" if fixed_version else package
        return {"name": name, "state": "present" if fixed_version else "latest"}
    # arch/pacman and generic fallback don't cleanly support version pins here
    return {"name": package, "state": "latest"}


def _pkg_module(os_family: str) -> str:
    return _PKG_MODULE.get(os_family, "ansible.builtin.package")


def _epss_suffix(c: CVEMatch) -> str:
    if c.epss_score is None or c.epss_percentile is None:
        return ""
    return f" (EPSS {c.epss_score:.2f}, {c.epss_percentile:.0%}ile)"


def _cve_tasks(system: SystemInfo, findings: list[Finding]) -> list[dict]:
    module = _pkg_module(system.os_family)
    tasks = []
    for f in findings:
        if f.kind != "cve" or f.cve is None or f.package is None:
            continue
        c = f.cve
        target = c.fixed_version or "latest available"
        name = (
            f"Upgrade {f.package} ({c.installed_version} -> {target}) "
            f"- fixes {c.cve_id} [{c.severity}]{_epss_suffix(c)}"
        )
        tasks.append(
            {
                "name": name,
                module: _pkg_task_args(system.os_family, f.package, c.fixed_version),
                "tags": ["prescryb", "cve", c.cve_id.lower()],
            }
        )
    return tasks


def _compliance_roles(findings: list[Finding]) -> dict[str, str]:
    seen_roles: dict[str, str] = {}
    for f in findings:
        for ref in f.compliance:
            if ref.role:
                seen_roles.setdefault(ref.role, ref.note)
    return seen_roles


def _attack_lines(findings: list[Finding]) -> list[str]:
    seen: dict[str, str] = {}
    for f in findings:
        for ref in f.attack:
            if ref.technique_id in seen:
                continue
            line = (
                f"{ref.technique_id} {ref.technique_name} "
                f"({ref.tactic}) - {ref.technique_url}"
            )
            if ref.mitigation_id:
                line += f" | mitigation {ref.mitigation_id} {ref.mitigation_name}"
            seen[ref.technique_id] = line
    return list(seen.values())


def _build_header(
    system: SystemInfo,
    findings: list[Finding],
    tasks: list[dict],
    seen_roles: dict[str, str],
    attack_lines: list[str],
) -> list[str]:
    target = f"{system.distro_id} {system.distro_version}, family={system.os_family}"
    generated = datetime.now(UTC).isoformat(timespec="seconds")
    header = [
        "# Generated by prescryb - SUGGESTION ONLY. Review with "
        "`ansible-playbook --check --diff`",
        "# before applying; prescryb does not execute playbooks itself.",
        f"# Target: {system.hostname}  ({target})",
        f"# Generated: {generated}",
        "#",
    ]
    for f in findings:
        if f.kind == "cve" and f.cve:
            summary = f.cve.summary[:140]
            header.append(
                f"# {f.cve.cve_id} ({f.cve.severity}){_epss_suffix(f.cve)} "
                f"on {f.package}: {summary}"
            )
            header.extend(f"#   ref: {ref}" for ref in f.cve.references[:3])
        else:
            header.append(f"# {f.title}: {f.detail[:140]}")
    if seen_roles:
        header.append("#")
        header.append(
            "# Compliance mapping (CIS / DISA STIG topic areas - see role docs "
            "for specifics):"
        )
        header.extend(f"#   {role}: {note}" for role, note in seen_roles.items())
    if attack_lines:
        header.append("#")
        header.append("# MITRE ATT&CK mapping (techniques mitigated by this change):")
        header.extend(f"#   {line}" for line in attack_lines)
    if not tasks and not seen_roles and not attack_lines:
        header.append("# No actionable findings - nothing to remediate.")
    return header


def build_playbook(
    system: SystemInfo, findings: list[Finding], hosts_alias: str | None = None
) -> str:
    """Render `findings` into a suggest-only Ansible playbook with a review header."""
    hosts_alias = hosts_alias or system.hostname
    tasks = _cve_tasks(system, findings)
    seen_roles = _compliance_roles(findings)
    attack_lines = _attack_lines(findings)

    play: dict = {
        "name": f"prescryb remediation for {hosts_alias}",
        "hosts": hosts_alias,
        "become": True,
    }
    if tasks:
        play["tasks"] = tasks
    if seen_roles:
        play["roles"] = [
            f"konstruktoid.hardening.{role}" for role in sorted(seen_roles)
        ]

    header = _build_header(system, findings, tasks, seen_roles, attack_lines)
    body = yaml.dump([play], sort_keys=False, default_flow_style=False, width=100)
    body = _blank_line_between_tasks(body)
    return "\n".join(header) + "\n---\n" + body


def _blank_line_between_tasks(body: str) -> str:
    """Insert a blank line before each task item (but not the first) for readability."""
    lines = body.splitlines()
    out: list[str] = []
    for line in lines:
        if line.startswith("  - name: ") and out and out[-1].strip() != "tasks:":
            out.append("")
        out.append(line)
    return "\n".join(out) + "\n"
